### PR TITLE
Preparations for #4

### LINKED ISSUE #4: Use sendPluginCommand as messaging system
https://github.com/dehesselle/dayzsrvip/blob/master/ts3psdk/include/ts3_functions.h#L254

https://github.com/Bluscream/ts3_sdk_c/blob/master/src/plugin.c#L1025

Please use this instead of channel messages.

### PR DESCRIPTION
**Pull request by Bluscream**
#4

### CODE REVIEW

**Comment by dehesselle** [comment]
I've taken some time to carefully review your PR. There are some good ideas/enhancements in there that will eventually end up in dayzsrvip - however, not with this PR.

Please don't be offended or disappointed, work with me here.

First off - I'm not perfect and I'm not claiming to be. I also don't think that "my way" of doing things is "the ultimate way", it's just "my way". I still have to learn a lot and "my way" does change more or less frequently with experience and knowledge (and, sadly, the arguable "taste" is also a factor).

But I try to stick to some rules/guidelines and I expect contributers to adapt. Granted, those rules/guidelines are nowhere to be found right now. That's because this project is still in its infancy and like 99,9% of all coders out there, I'd like to get something running first before spending excessive amounts of time with documentation. That being said, your willingness to contribute comes unexpected but is appreciated (I wish I'd have been more prepared/ready).

There is now a document `CONTRIBUTE.md` in the `doc` folder. Please read it.

Now, let's get into some details regarding your PR:
1. You have at least one syntactical error in your code. This leads me to believe that you did not even compile it prior to submitting the PR. That's a big no-no. See `plugin.cc`, line 453: `pluginName` is a `char*`
2. The function `DayzServerIp::getProcess()` is not only C-style (I don't fault you for that, you couldn't have known) but also copy-pasted from some Unix code. There is no `/proc` filesystem in Windows. If it does compile, it'll never work.
3. If you didn't compile your code, you obviously didn't test it. Also a big no-no.

Many people would consider these three things alone as offensive - it looks like you carelessly dumped a load of untested (and broken!) stuff into someone's front yard. It doesn't do you any good, it only hurts your reputation. Please take your time, don't rush things and treat contributing to someone else's work more seriously in the future. A good rule of thumb is to be even more cautious than you are with your own stuff.

That being said, I like the idea of checking "Is DayZ running?" and using `sendPluginCommand()`. I am new to the TS3 API and sending text messages was the first thing that came to my mind when looking at it.  
So `sendPluginCommand()` will eventually take over the part of the clients updating each other, but sending text messages to the channel (just for information) will stay in as on optional feature. This is due to feedback I've received from my few testers who actually close the plugin GUI and only want to look at TS3 chat. That's obviously not what I was going for and their opinion is not representative, but it matters.

If you're still with me, that's a good sign. Now, where do we go from here? My suggestion is that I take your PR as inspiration/feature request and will implement the functionalities myself, according to my standards. Depending on my spare time this will take a few days or weeks, but will happen this month.

**Comment by Bluscream** [comment]
Don't take this too personal:

Do you really expect willing someone to help you out if you present them such a ruleset? I don't.

Of course i know that my changes are not final, thats why i appended "(needs adjustment)".
But i think i gave you a pretty good idea of what i would change and how pluginCommands would work in your project.

It took my almost 2 hours to collect and implement these changes to your code and i couldn't test it because i simply have no PC that could run Visual Studio and Qt Creator.

This was actually the first time i created such a PR that isn't a fork update and it probably will be the last. Your statement changed my mind from being your contributor who serves you ideas on a silver tablet to being your user just creating issues and waiting for you to look things up and implememt them "your way".

I would even have had no problem with you rejectig the PR and telling me something (Hey i can't implement everythink but i will definitly look through it and take the parts that are nessesary, Thank you :) but you just criticise all my work which just isn't fair. I'm open for constructive feedback on my work but not in the context where i spent my spare time helping others out.

Imagine you helping a friend out with computer issues via Teamviewer for 2 hours and when you're done he would just tell you that your fixes are worse and reverts them.
> Sent from [my Samsung Galaxy Tab 9.3](http://valid.x86.fr/a/4ylsyy).

**Comment by dehesselle** [comment]
> Do you really expect willing someone to help you out if you present them such a ruleset? I don't.

I don't expect anyone to help me - in fact, I didn't come here asking for help.

But I do expect everyone to follow house rules - and so does everybody else (as in: project maintainers) for that matter. Please use [this article](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) to educate yourself on contribution guidelines in general and especially take a look at the examples at the bottom of that article. You'll see that the bigger the project, the more detailed the contribution guidelines become. In comparison, what I'm asking is rather trivial. And except for "my coding style", all the other items usually go without saying for developers that have at least a little experience.

> Of course i know that my changes are not final, thats why i appended "(needs adjustment)".
But i think i gave you a pretty good idea of what i would change and how pluginCommands would work in your project.

Yes, you did. And I complimented you on that with my first sentence and again later in the second last paragraph. I like those ideas.  
But you just don't submit unfinished/untested/broken stuff deliberately. Ever.

> It took my almost 2 hours to collect and implement these changes to your code and i couldn't test it because i simply have no PC that could run Visual Studio and Qt Creator.

I'm sorry, but it's hardly my fault that you did not contact me before getting involved. There is no consolation price for "but I tried so hard" if you're way off target. You either do it the right way or you better don't do it at all (or at least ask beforehand!). Nobody will want to work with you if rushing untested code (that doesn't even compile) out the door is your mindset. And if you don't have the tools, don't try to build a house.  
On the off-chance you do find someone who enjoys cleaning up after you and fixing your stuff, because you didn't do it for whatever reason, keep him/her close.

> This was actually the first time i created such a PR that isn't a fork update and it probably will be the last. Your statement changed my mind from being your contributor who serves you ideas on a silver tablet to being your user just creating issues and waiting for you to look things up and implement them "your way".

If you're discouraged that quickly and not willing to try to fit in, then you never doing a PR again is really for the best. Don't join a team if you're not willing to take a subordinate role at first. No one wants that kind of help you're offering and you'll only be disappointed and angry at others.  
Yes, you've brought in good ideas. And I told you right away how I feel about them. Do you think you're the only one with ideas? Why do you think this is a v0.x? Has this project already been in development for months/years?

> I would even have had no problem with you rejectig the PR and telling me something (Hey i can't implement everythink but i will definitly look through it and take the parts that are nessesary, Thank you :) but you just criticise all my work which just isn't fair. I'm open for constructive feedback on my work but not in the context where i spent my spare time helping others out.

I think I did exactly what you're asking here. I told you that I like your ideas. I told you that they will be implemented eventually, but not with your PR. I gave you constructive feedback on what is wrong with your PR and that untested, broken code is not the way to build a working relationship. I suggested that I take your PR and build on your ideas.  
But you would have preferred me closing your PR, just leaving a "Thank you :) I'll take it into consideration" instead of a sophisticated answer that's clearly a sign of me trying to work with/not giving up on you?

> Imagine you helping a friend out with computer issues via Teamviewer for 2 hours and when you're done he would just tell you that your fixes are worse and reverts them.

That's unfortunate, but actually happens in real life.

You have good intentions, but if your help actually makes things worse (e.g. you "polluting" my code so it does not compile and introduces crashes) you still expect me to accept it? You're totally misconceiving how you come across.

In the end, me having to correct some indentation, renaming variables etc. to my liking is not a cause for rejection, but I want to see that you put in some effort. And you didn't. To stay with your analogy: two hours of half-assed help over TeamViewer is not appreciated.

---

I am not angry with you and neither should you with me - that is not my intention. I'd bet that you are not a professional software developer, and that is not a problem at all, but it'd explain how we think and perceive each other so differently. I tried my best to explain myself to you in a polite manner. Your first response shows that I managed to offend you anyway. This probably won't change with this response of mine.

If you think you're right and I'm wrong, so be it. In that case, please leave in peace and don't come back. I'm not going to discuss this any further.

**Comment by Bluscream** [comment]
I don't think you're wrong, personally i love some of the rules (like short and describing commit messages) but i think every little help and tip is worh some credit

**Comment by dehesselle** [comment]
It is - I'm sorry if you didn't feel that way. I'm not without fault, I'm trying.

**Comment by Bluscream** [comment]
<3

**Comment by dehesselle** [comment]
FWIW, I shared our conversation with a friend of mine and he pointed out a few things to me where I have had good intentions, but chose my words poorly (as in: "this is poisonous").  
So... there's much to learn. As always.

**Comment by Bluscream** [comment]
1 minute effort: see the reaction https://github.com/juancarlospaco/css-html-js-minify/pull/46#issuecomment-265117063 xD

**Pull request closed without merging**
